const fileInput=document.getElementById('fileInput');
const chooseBtn=document.getElementById('chooseBtn');
const dropZone=document.getElementById('dropZone');
const preview=document.getElementById('preview');
const fileName=document.getElementById('fileName');
const mediaType=document.getElementById('mediaType');
const downloadBtn=document.getElementById('downloadBtn');
const resetBtn=document.getElementById('resetBtn');
const themeBtn=document.getElementById('themeBtn');
const iconCards=[...document.querySelectorAll('.icon-card')];
const sizeRange=document.getElementById('sizeRange');
const xRange=document.getElementById('xRange');
const yRange=document.getElementById('yRange');
const sizeValue=document.getElementById('sizeValue');
const xValue=document.getElementById('xValue');
const yValue=document.getElementById('yValue');
const currentTimeInput=document.getElementById('currentTimeInput');
const durationInput=document.getElementById('durationInput');
const timeBarToggle=document.getElementById('timeBarToggle');
const miniPlayToggle=document.getElementById('miniPlayToggle');
let selectedFile=null,selectedStyle='classic',mediaUrl=null,currentMedia=null,selectedColor='#ffffff';
const styleMap={classic:['circle','#fff','#101827'],outline:['circle','rgba(0,0,0,.35)','#fff'],glass:['circle','rgba(255,255,255,.18)','#fff'],square:['round','#fff','#101827'],soft:['circle','#eaf1ff','#24324b'],neon:['circle','#0b1320','#fff'],double:['circle','#111a2b','#fff'],minimal:['none','transparent','#fff'],pill:['pill','#fff','#101827'],diamond:['diamond','#fff','#101827'],badge:['round','#fff','#101827'],floating:['circle','#fff','#101827']};
function fmt(sec){if(!Number.isFinite(sec))return'0:00';sec=Math.max(0,Math.floor(sec));const m=Math.floor(sec/60),s=sec%60;return `${m}:${String(s).padStart(2,'0')}`}
function parseTime(v){const p=String(v||'0:00').split(':').map(Number);return p.length>=2?(p[0]||0)*60+(p[1]||0):(p[0]||0)}
function updateLabels(){sizeValue.textContent=`${sizeRange.value}px`;xValue.textContent=`${xRange.value}%`;yValue.textContent=`${yRange.value}%`}
function addPreviewTimebar(){const old=preview.querySelector('.timebar-overlay');if(old)old.remove();if(!timeBarToggle.checked)return;const cur=parseTime(currentTimeInput.value),dur=parseTime(durationInput.value),pct=dur?Math.min(100,Math.max(0,cur/dur*100)):13;const bar=document.createElement('div');bar.className='timebar-overlay';bar.innerHTML=`${miniPlayToggle.checked?'<span class="tiny-play">▶</span>':''}<span class="time-text">${currentTimeInput.value||'0:00'}</span><span class="track"></span><span class="time-text">${durationInput.value||'0:00'}</span><span class="tool">🔊</span><span class="tool">⛶</span><span class="tool">⋮</span>`;bar.querySelector('.track').style.setProperty('--pct',pct+'%');bar.querySelector('.track').style.background=`linear-gradient(to right,#fff ${pct}%,#999 ${pct}%)`;preview.appendChild(bar)}
function renderPreview(){if(mediaUrl){URL.revokeObjectURL(mediaUrl);mediaUrl=null}currentMedia=null;if(!selectedFile){preview.innerHTML='<div class="empty-preview"><div>◉</div><span>Your media preview appears here</span></div>';mediaType.textContent='Waiting for media';downloadBtn.disabled=true;return}mediaUrl=URL.createObjectURL(selectedFile);const isVideo=selectedFile.type.startsWith('video/');preview.innerHTML='';const media=document.createElement(isVideo?'video':'img');media.className='media-element';media.src=mediaUrl;media.playsInline=true;media.preload='metadata';media.controls=false;if(isVideo){currentMedia=media;media.addEventListener('loadedmetadata',()=>{durationInput.value=fmt(media.duration);currentTimeInput.value=fmt(media.currentTime);addPreviewTimebar()});media.addEventListener('timeupdate',()=>{currentTimeInput.value=fmt(media.currentTime);addPreviewTimebar()});media.addEventListener('click',()=>media.paused?media.play():media.pause())}else currentMedia=media;preview.appendChild(media);const icon=document.createElement('div');icon.className=`overlay-icon ${selectedStyle}`;preview.appendChild(icon);updateIcon();mediaType.textContent=isVideo?'Video preview':'Image preview';downloadBtn.disabled=false;addPreviewTimebar()}
function updateIcon(){const icon=preview.querySelector('.overlay-icon');if(!icon)return;icon.className=`overlay-icon ${selectedStyle}`;icon.style.width=`${sizeRange.value}px`;icon.style.height=selectedStyle==='pill'?`${Math.max(38,Number(sizeRange.value)*.55)}px`:`${sizeRange.value}px`;icon.style.left=`${xRange.value}%`;icon.style.top=`${yRange.value}%`;applyColorToIcon(icon)}
function applyColorToIcon(icon){if(!icon)return;const c=selectedColor;const dark=['#ffffff','#f8fafc','#eaf1ff'].includes(c.toLowerCase())?'#101827':'#fff';icon.style.color=dark;icon.style.background=selectedStyle==='minimal'?'transparent':c;icon.style.borderColor=c;if(selectedStyle==='neon')icon.style.boxShadow=`0 0 10px ${c},0 0 28px ${c},0 0 55px ${c}66`;else if(selectedStyle==='outline'||selectedStyle==='double')icon.style.background='transparent';else icon.style.boxShadow='0 10px 28px #0008'}
function setFile(file){if(!file)return;const valid=file.type.startsWith('image/')||file.type.startsWith('video/');if(!valid){fileName.textContent='Please choose an image or video file';return}selectedFile=file;fileName.textContent=file.name;renderPreview()}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawPlay(ctx,cx,cy,size,style){const s=styleMap[style]||styleMap.classic;const shape=s[0];ctx.save();ctx.translate(cx,cy);if(shape==='diamond')ctx.rotate(Math.PI/4);if(['classic','soft','pill','diamond','badge','floating','square'].includes(style)){ctx.shadowColor='rgba(0,0,0,.5)';ctx.shadowBlur=size*.22;ctx.shadowOffsetY=size*.1}const dark=['#ffffff','#f8fafc','#eaf1ff'].includes(selectedColor.toLowerCase())?'#101827':'#fff';ctx.fillStyle=selectedColor;ctx.strokeStyle=selectedColor;ctx.lineWidth=Math.max(3,size*.055);if(shape==='circle'){ctx.beginPath();ctx.arc(0,0,size/2,0,Math.PI*2);if(style!=='minimal'&&style!=='outline'&&style!=='glass')ctx.fill();if(style==='neon'||style==='outline'||style==='double'||style==='glass')ctx.stroke()}else if(shape==='round'){roundRect(ctx,-size/2,-size/2,size,size,size*.2);ctx.fill()}else if(shape==='pill'){roundRect(ctx,-size*.75,-size*.36,size*1.5,size*.72,size*.36);ctx.fill()}else if(shape==='diamond'){roundRect(ctx,-size*.38,-size*.38,size*.76,size*.76,size*.12);ctx.fill()}ctx.shadowColor='transparent';ctx.fillStyle=dark;ctx.font=`800 ${Math.round(size*.42)}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('▶',0,1);if(style==='double'){ctx.globalAlpha=.4;ctx.beginPath();ctx.arc(0,0,size*.64,0,Math.PI*2);ctx.stroke()}if(style==='neon'){ctx.globalAlpha=.55;ctx.shadowColor=selectedColor;ctx.shadowBlur=size*.3;ctx.beginPath();ctx.arc(0,0,size/2,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawTimebar(ctx,w,h){if(!timeBarToggle.checked)return;const bh=Math.max(54,Math.round(h*.09)),y=h-bh,pad=Math.max(14,w*.018),font=Math.max(12,w*.012);const g=ctx.createLinearGradient(0,y,0,h);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.35,'rgba(0,0,0,.6)');g.addColorStop(1,'rgba(0,0,0,.94)');ctx.fillStyle=g;ctx.fillRect(0,y,w,bh);let x=pad;const ty=y+bh*.62;ctx.fillStyle='#fff';ctx.textBaseline='middle';if(miniPlayToggle.checked){ctx.font=`800 ${font*1.35}px Arial`;ctx.fillText('▶',x,ty);x+=font*1.9}ctx.font=`600 ${font}px Arial`;const left=currentTimeInput.value||'0:00',right=durationInput.value||'0:00';ctx.fillText(left,x,ty);x+=ctx.measureText(left).width+font;const rw=ctx.measureText(right).width,end=w-pad-rw-font*8;const tw=Math.max(50,end-x);const cur=parseTime(left),dur=parseTime(right),pct=dur?Math.min(1,Math.max(0,cur/dur)):0.13;ctx.lineCap='round';ctx.lineWidth=Math.max(3,bh*.065);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.beginPath();ctx.moveTo(x,ty);ctx.lineTo(x+tw,ty);ctx.stroke();ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(x,ty);ctx.lineTo(x+tw*pct,ty);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x+tw*pct,ty,Math.max(5,bh*.12),0,Math.PI*2);ctx.fill();ctx.font=`600 ${font}px Arial`;ctx.fillText(right,x+tw+font,ty);ctx.font=`${font*1.35}px Arial`;ctx.fillText('🔊',x+tw+font*3,ty);ctx.fillText('⛶',x+tw+font*5.5,ty);ctx.fillText('⋮',x+tw+font*7.5,ty)}
async function saveImage(){if(!selectedFile||!currentMedia)return;const w=currentMedia.videoWidth||currentMedia.naturalWidth,h=currentMedia.videoHeight||currentMedia.naturalHeight;if(!w||!h)return;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(currentMedia,0,0,w,h);const px=w*Number(xRange.value)/100,py=h*Number(yRange.value)/100;drawPlay(ctx,px,py,Math.min(Number(sizeRange.value),Math.min(w,h)*.5),selectedStyle);drawTimebar(ctx,w,h);const a=document.createElement('a');a.download=`media-thumbnail-${Date.now()}.png`;a.href=canvas.toDataURL('image/png');document.body.appendChild(a);a.click();a.remove()}
chooseBtn.addEventListener('click',()=>fileInput.click());dropZone.addEventListener('dragover',e=>{e.preventDefault();dropZone.style.borderColor='#8db5ff'});dropZone.addEventListener('dragleave',()=>dropZone.style.borderColor='#33445f');dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.style.borderColor='#33445f';setFile(e.dataTransfer.files[0])});fileInput.addEventListener('change',()=>setFile(fileInput.files[0]));
iconCards.forEach(card=>card.addEventListener('click',()=>{iconCards.forEach(c=>c.classList.remove('active'));card.classList.add('active');selectedStyle=card.dataset.style;updateIcon()}));
[sizeRange,xRange,yRange].forEach(el=>el.addEventListener('input',()=>{updateLabels();updateIcon()}));[currentTimeInput,durationInput].forEach(el=>el.addEventListener('input',addPreviewTimebar));[timeBarToggle,miniPlayToggle].forEach(el=>el.addEventListener('change',addPreviewTimebar));downloadBtn.addEventListener('click',saveImage);
resetBtn.addEventListener('click',()=>{if(mediaUrl)URL.revokeObjectURL(mediaUrl);mediaUrl=null;currentMedia=null;selectedFile=null;fileInput.value='';fileName.textContent='No file selected';selectedStyle='classic';selectedColor='#ffffff';sizeRange.value=88;xRange.value=50;yRange.value=50;currentTimeInput.value='0:02';durationInput.value='2:49';timeBarToggle.checked=true;miniPlayToggle.checked=true;iconCards.forEach(c=>c.classList.toggle('active',c.dataset.style==='classic'));updateLabels();renderPreview()});themeBtn.addEventListener('click',()=>{document.body.classList.toggle('light');themeBtn.textContent=document.body.classList.contains('light')?'☾':'☼'});updateLabels();

/* Compact premium controls: play-button color picker + smaller page spacing */
const compactStyle=document.createElement('style');compactStyle.textContent=`.hero{max-width:920px;margin-top:38px}.hero h1{font-size:clamp(34px,5vw,58px);margin:14px 0}.hero-copy{font-size:14px;max-width:650px}.studio-card{max-width:900px;margin-top:24px;padding:10px;border-radius:18px}.preview{min-height:260px;max-height:520px}.icons-section,.how-section{max-width:1050px;margin-top:70px}.icon-grid{grid-template-columns:repeat(6,1fr);gap:9px;margin-top:24px}.icon-card{padding:10px;border-radius:12px}.icon-number{margin-bottom:7px}.icon-preview{width:54px;height:54px;margin-bottom:8px;font-size:19px}.icon-card strong{font-size:12px}.icon-card small{font-size:9px}.editor-controls{gap:9px}.control-box{padding:11px}.color-control{grid-column:1/-1}.color-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.color-dot{width:31px;height:31px;border-radius:50%;border:2px solid transparent;cursor:pointer;box-shadow:0 2px 8px #0006}.color-dot.active{outline:2px solid #8db5ff;outline-offset:3px}.color-picker{width:36px;height:31px;border:0;background:transparent;padding:0;cursor:pointer}.style-mini-title{font-size:11px;color:#dce8f8;font-weight:800;margin-bottom:9px}.studio-card .upload-zone{padding:20px}.preview-wrap{margin-top:10px;padding:11px}@media(max-width:900px){.icon-grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:700px){.hero h1{font-size:34px}.icon-grid{grid-template-columns:repeat(3,1fr)}.preview{min-height:220px}}`;document.head.appendChild(compactStyle);
const controls=document.querySelector('.editor-controls');
if(controls&&!document.getElementById('colorControl')){const box=document.createElement('div');box.className='control-box color-control';box.id='colorControl';box.innerHTML=`<div class="style-mini-title">PLAY BUTTON COLOR</div><div class="color-row"><button class="color-dot active" data-color="#ffffff" style="background:#fff"></button><button class="color-dot" data-color="#ff3b4f" style="background:#ff3b4f"></button><button class="color-dot" data-color="#1687ff" style="background:#1687ff"></button><button class="color-dot" data-color="#19c96b" style="background:#19c96b"></button><button class="color-dot" data-color="#ffd21c" style="background:#ffd21c"></button><button class="color-dot" data-color="#ff4fa3" style="background:#ff4fa3"></button><button class="color-dot" data-color="#713cff" style="background:#713cff"></button><input class="color-picker" id="customColor" type="color" value="#ffffff" title="Custom color"></div>`;controls.prepend(box);box.querySelectorAll('.color-dot').forEach(btn=>btn.addEventListener('click',()=>{box.querySelectorAll('.color-dot').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedColor=btn.dataset.color;updateIcon()}));document.getElementById('customColor').addEventListener('input',e=>{box.querySelectorAll('.color-dot').forEach(b=>b.classList.remove('active'));selectedColor=e.target.value;updateIcon()})}
